### ISSUE TITLE
Cannot download the pre-trained policy checkpoints

### ISSUE THREAD

**Issue by student-petercai** [rpartsey/pointgoal-navigation#5]
The links in the Navigation Policy secion are not working

**Comment by rpartsey** [comment]
Good catch :)
Thanks for opening the issue. I've already updated links to nav-policy checkpoints.
All the checkpoints and generated mp3d PointNav-v2 episodes are also shared in [this](https://drive.google.com/drive/folders/1qe0J-lPzPNnWLeERtjZNkxSq4M0qct2z?usp=sharing) google drive folder.
